export const kyThuat = [
  'Tôi thường ra quyết định một cách độc lập',
  'Tôi thường suy nghĩ cân đối với nguồn lực hiện có để đưa ra quyết định',
  'Tôi dễ dàng thích nghi với môi trường mới',
  'Tôi nhanh chóng vận hành các máy móc',
  'Tôi thích làm các công việc thủ công như thêu thùa, may vá, đan móc...',
  'Tôi không thích các công việc đòi hỏi phải đọc sâu, nghiên cứu, tôi thích các công việc tay chân hoặc sử dụng kỹ năng',
  'Tôi thích trồng cây và làm vườn',
  'Tôi thấy có động lực khi công việc tôi làm cho kết quả trực quan ngay',
  'Tôi thích làm việc ngoài trời hơn là trong phòng học, văn phòng',
  'Tôi thích trang điểm, chăm sóc bản thân và người khác',
  'Tôi thích tự tìm hiểu cách sửa chữa các đồ vật bị hỏng trong nhà',
  'Tôi thích khám phá cấu tạo của các đồ gia dụng điện tử, điện lạnh trong nhà',
  'Tôi không thích làm việc trong văn phòng',
  'Tôi thích làm những việc có thể hoàn thành bằng tay chân (cho dù yêu cầu tỉ mỉ) hơn là những công việc phải suy nghĩ, nghiên cứu nhiều.',
  'Tôi là người hướng nội, khó hòa nhập với môi trường mới',
  'Tôi thích tự lắp ráp các đồ gia dụng trong gia đình như đồ gỗ, đồ điện tử, máy vi tính',
  'Tôi thích tìm hiểu về loa đài',
  'Tôi hay tò mò về bất cứ thứ gì xung quanh mình (Thiên nhiên, khoa học kỹ thuật, không gian;...)',
  'Tôi thích tự chăm sóc vườn hoa theo hướng dẫn của sách hoặc trên internet',
  'Tôi thích gấp giấy origami trong thời gian rảnh theo hướng dẫn của internet hoặc sách hướng dẫn',
  'Tôi thích tự sửa xe máy, xe đạp, đồ chơi điện tử trước khi nhờ sự trợ giúp của người khác',
  'Tôi thích sắp xếp, dọn dẹp nhà cửa',
  'Tôi thích đạp xe như một môn thể thao',
  'Tôi thích nuôi thú cưng',
  'Tôi thích tham gia du lịch thám hiểm (như leo núi, khám phá rừng nguyên sinh..) hơn là du lịch nghỉ dưỡng',
  'Tôi thường tư duy rành mạch, rõ ràng, không thích lòng vòng',
  'Thường nói thẳng suy nghĩ của mình, không nói giảm, nói tránh',
  'Khi học phổ thông, tôi thích học các môn toán, toán tin, công nghệ',
  'Tôi thấy hứng thú với việc sửa chữa đồ gia dụng như lò vi sóng, lò sửa, máy sấy',
  'Tôi thích tìm hiểu cấu tạo của xe máy, xe oto',
  'Tôi thường chọn hoạt động giải trí là chơi game trên máy tính thay vì đọc báo, truyện cười',
  'Tôi thấy thích thú với công việc thủ'
]

export const nghienCuu = [
  'Tôi thích tìm hiểu và khám phá về các vấn đề mới',
  'Tôi có chính kiến riêng và rất khó để thay đổi nếu đã tìm hiểu và tin tưởng vào điều gì',
  'Tôi có khả năng suy nghĩ một cách mạch lạc, chặt chẽ',
  'Tôi thích thực hiện các thí nghiệm và nghiên cứu',
  'Tôi có khả năng tổng hợp thông tin và dữ liệu',
  'Tôi thích những hoạt động phân loại, kiểm tra, đánh giá',
  'Tôi tự tổ chức công việc mình phải làm',
  'Tôi có thể quan sát và đánh giá các sự việc xung quanh một cách khách quan',
  'Tôi có khả năng giải quyết và xử lý các vấn đề khó',
  'Tôi tò mò và thích tìm hiểu về mọi thứ xung quanh',
  'Tôi thích học Văn nghị luận, phân tích và lập luận',
  'Tôi có thể tìm hiểu rất sâu một vấn đề mình quan tâm',
  'Tôi cảm thấy mình có suy nghĩ và hành vi già dặn hơn các bạn',
  'Tôi thích đọc sách về chủ đề khoa học',
  'Tôi thích giải những đề toán có độ khó cao.',
  'Tôi thích các hoạt động liên quan đến điều tra, truy tìm manh mối.',
  'Tôi thích xem các bộ phim chủ đề trinh thám, thám tử,...',
  'Tôi có sở thích sưu tập (thẻ bài, tiền xu, tem...)',
  'Tôi thích các trò chơi ô chữ, giải đố',
  'Tôi muốn tìm hiểu nhiều hơn về trái đất và các hành tinh trong hệ mặt trời',
  'Tôi thích tìm hiểu về vũ trụ và sự chuyển động của các vì sao',
  'Tôi thích tìm hiểu về văn hóa các quốc gia trên thế giới',
  'Tôi thích tìm hiểu về tâm lý học và hành vi của con người',
  'Tôi thích các chương trình về chủ đề khoa học viễn tưởng',
  'Tôi thích đọc báo hay xem tin tức về khoa học, địa lý, lịch sử',
  'Tôi có khả năng học các môn thuộc khối tự nhiên khá tốt',
  'Tôi cảm thấy hào hứng khi được tiếp thu những kiến thức mới',
  'Tôi hay tìm hiểu về lịch sử, nguồn gốc loài người',
  'Tôi thích đọc các bài báo về khoa học công nghệ',
  'Tôi thích đọc sách báo, xem phim tài liệu về thế giới động vật',
  'Tôi quan tâm đến việc phát minh ra các sản phẩm mới',
  'Tôi có thể phân tích một vấn đề rõ ràng, cụ thể, và có chính kiến riêng',
  'Tôi thường không thể quyết định nhanh vì luôn muốn tìm hiểu đầy đủ thông tin hơn',
  'Tôi thích tự tìm hiểu về chủ đề mình thích qua sách báo hoặc video',
  'Tôi dành nhiều thời gian tìm tòi nghiên cứu các chủ đề mà mình quan tâm',
  'Tôi thường quan sát và phân tích sự vật, sự việc xung quanh',
  'Tôi hay tự đặt nhiều câu hỏi về các vấn đề trong cuộc sống',
  'Tôi có khả năng lý giải vấn đề một cách khoa học, hợp lý',
  'Tôi thường hay đọc sách báo hoặc tin tức về những phát hiện khoa học mới',
  'Tôi là người rất hay để ý tới chi tiết và cẩn thận',
  'Tôi muốn tìm hiểu về cách giảm ô nhiễm môi trường',
  'Tôi thấy hứng thú khi tìm hiểu về vũ trụ và sự hình thành của các hành tinh',
  'Tôi thích một buổi tham quan viện bảo tàng khoa học hoặc lịch sử',
  'Tôi thích tự lên kế hoạch và phương pháp học riêng của bản thân',
  'Tôi không hứng thú lắm khi tham gia các hoạt động xã giao'
]

export const ngheThuat = [
  'Tôi là người dễ xúc động',
  'Tôi có óc tưởng tượng phong phú',
  'Tôi thích sự tự do, không theo những quy định, quy tắc',
  'Tôi có khả năng thuyết trình, diễn xuất',
  'Tôi có thể chụp hình hoặc vẽ tranh, trang trí, điêu khắc',
  'Tôi có năng khiếu âm nhạc',
  'Tôi có khả năng viết, trình bày những ý tưởng của mình',
  'Tôi thích làm những công việc mới, những công việc đòi hỏi sự sáng tạo',
  'Tôi thoải mái bộc lộ những ý thích',
  'Tôi là người đa sầu đa cảm, dễ xúc động và không giỏi kiềm chế cảm xúc.',
  'Tôi có trí tưởng tượng vô cùng phong phú.',
  'Tôi thích cuộc sống tự do, không bị bó buộc và khuôn khổ hay quy tắc nào.',
  'Tôi thích các hoạt động văn nghệ như ca hát, diễn xuất, MC,...',
  'Tôi thích chụp hình, vẽ tranh, trang trí, điêu khắc;...',
  'Tôi thích tự thiết kế hoặc tự chọn; phối quần áo cho mình và người khác.',
  'Tôi không thích làm những công việc rập khuôn, lập đi lập lại nhiều lần, không có sự sáng tạo.',
  'Tôi thích âm nhạc và không thể sống nếu thiếu chúng.',
  'Tôi dễ bị hấp dẫn bởi cái đẹp (Một gương mặt đẹp, một bức tranh đẹp, một bài hát hay,...)',
  'Tôi có một tâm hồn khá mơ mộng và tôi thích thế.',
  'Tạo ra một tác phẩm nghệ thuật, tranh, câu chuyện',
  'Viết truyện ngắn',
  'Chứng tỏ năng lực nghệ thuật của bản thân với người khác (nói lên suy nghĩ/quan điểm qua tác phẩm nghệ thuật)',
  'Chơi trong một ban nhạc',
  'Chỉnh sửa phim',
  'Thuyết trình hoặc thiết kế, theo ý tưởng của mình',
  'Vẽ phim hoạt hình',
  'Hát trong một ban nhạc',
  'Biểu diễn nhảy hiện đại',
  'Dẫn chương trình (MC) cho một sự kiện',
  'Độc thoại hay kể chuyện trên đài phát thanh/phần mềm',
  'Viết kịch bản cho phim hoặc chương trình truyền hình',
  'Chụp ảnh cho các sự kiện trong cuộc sống hoặc sự kiện nghệ thuật',
  'Viết một bài phê bình phim cho bộ phim mình thích/ghét nhất',
  'Tham gia câu lạc bộ âm nhạc, hội họa, văn nghệ',
  'Minh họa các ý tưởng qua hình ảnh hoặc điệu bộ',
  'Sáng tạo nội dung (âm nhạc, bài văn, tranh ảnh, v.v.) theo cảm hứng',
  'Học chơi nhạc cụ',
  'Phác họa và vẽ tranh',
  'Thiết kế bìa sách cho một cuốn sách mình thích',
  'Soạn hay mix nhạc',
  'Chơi nhạc cụ trong một ban nhạc',
  'Tạo những bức ảnh sáng tạo',
  'Vẽ minh họa một câu chuyện trên mạng, báo, hay trong sách',
  'Viết các bài trên trang mạng xã hội hay Blog cá nhân',
  'Giải trí cho người khác bằng cách kể chuyện hay kể chuyện cười',
  'Tham gia hoạt động nghệ thuật (ca hát, nhạc họa v.v.)',
  'Chỉnh sửa phim',
  'Tạo hiệu ứng đặc biệt cho phim',
  'Biểu diễn nhảy/khiêu vũ một mình hay trong nhóm',
  'Chứng tỏ năng lực nghệ thuật của bản thân với người khác (nói lên suy nghĩ/quan điểm qua tác phẩm nghệ thuật)',
  'Làm người mẫu chụp hình quảng cáo hay quay phim quảng cáo',
  'Tham gia vào các hoạt động nghệ thuật như phác thảo và vẽ tranh, v.v.',
  'Thường bị thu hút bởi những gì liên quan đến cái đẹp (người, quang cảnh, thời trang, vật dụng hàng ngày, v.v.)',
  'Dành thời gian rảnh để học một hay nhiều trong những môn sau: vẽ, chụp hình, âm nhạc, hát, đóng kịch, múa, nhảy, viết truyện, kể chuyện',
  'Tự chọn và mua trang phục cho bản thân',
  'Thường đọc sách, xem phim hay Youtube, nghe nhạc, xem kịch nghệ trong thời gian rảnh',
  'Thường chọc cười người khác bằng cách làm trò, biểu diễn, kể chuyện cười',
  'Thường có những ý tưởng mới và sáng tạo trong lĩnh vực các con quan tâm',
  'Có trí tưởng tượng phong phú từ khi còn rất nhỏ',
  'Thường có gu thẩm mỹ độc đáo, khác lạ',
  'Thường mất ít thời gian (so với những hoạt động khác) khi học một hay nhiều trong những môn sau: vẽ, chụp hình, âm nhạc, hát, đóng kịch, múa, nhảy, viết truyện, kể chuyện',
  'Thường thu hút sự chú ý của bạn bè chung lớp hay người xung quanh',
  'Thường xúc động trước các hoạt động nghệ thuật yêu thích',
  'Thường nhạy cảm trước cái đẹp',
  'Thường dao động giữa hai cung bậc cảm xúc vui buồn',
  'Thường nghĩ hay làm những điều tạo nét riêng cho bản thân (trang phục, trang điểm, chọn lựa nhạc, v.v.)'
]

export const xaHoi = [
  'Tôi luôn thân thiện với mọi người và chủ động giúp đỡ người khác',
  'Tôi thấy vui và hạnh phúc khi được giao tiếp với người khác',
  'Tôi thường hay xúc động khi xem các bộ phim tình cảm',
  'Tôi thích huấn luyện người khác, hoặc tư vấn, đưa ra lời khuyên về những vấn đề của người khác.',
  'Tôi thích được nghe bạn bè chia sẻ về những vấn đề cá nhân của họ.',
  'Tôi quan tâm đến các hoạt động chăm sóc sức khỏe cộng đồng',
  'Tôi thường tham gia các hoạt động thiện nguyện',
  'Tôi thường e ngại khi yêu cầu được trả công',
  'Tôi thích đưa ra lời khuyên hay trở thành người trung gian hoà giải khi có mâu thuẫn xảy ra trong nhóm bạn của mình.',
  'Tôi thường hay lo những chuyện bao đồng',
  'Tôi là người quảng giao',
  'Tôi là người tử tế, vô tư và không vụ lợi trong tất cả các giao dịch',
  'Tôi luôn biết cách động viên khích lệ người đối diện',
  'Tôi thích làm việc nhóm',
  'Tôi thường hay chiều lòng đón ý người khác',
  'Tôi thích các hoạt động thể thao mang tính đồng đội như: bóng rổ, bóng chuyền, bóng đá, kéo co...',
  'Tôi thích tham gia vào việc bảo vệ động vật hoang dã',
  'Tôi thích các hoạt động liên quan đến tái chế, hoạt động bảo vệ môi trường',
  'Tôi có nhiều bạn bè và thích lắng nghe bạn bè chia sẻ về cuộc sống của họ',
  'Tôi thường chia sẻ những kinh nghiệm của bản thân trong các lĩnh vực mà người đối diện quan tâm',
  'Tôi thích được bạn bè, người thân tìm đến tôi để nhờ giúp đỡ, trong trường hợp đó, tôi thường giúp đỡ hết khả năng của mình',
  'Tôi thường sẵn lòng dành thời gian để giúp đỡ người khác',
  'Tôi thường để dành một khoản nhỏ nhỏ hàng tháng cho hoạt động từ thiện cho những người có hoàn cảnh khó khăn với tinh thần lá lành đùm lá rách, lá rách ít đùm lá rách nhiều',
  'Tôi thích hoạt động Đoàn, Đội, Đảng',
  'Thích hướng dẫn người khác một kỹ năng mà mình biết hoặc kiến thức mà mình am hiểu',
  'Quan tâm đến cảm xúc của người khác khi tôi đưa ra quyết định có ảnh hưởng đến họ',
  'Tôi thích kể chuyện cười cho bạn bè nghe, giúp họ tăng năng lượng tích cực',
  'Tôi thường ưu tiên mong muốn của người khác trước mong muốn của bản thân',
  'Cảm xúc của tôi thường bị ảnh hưởng bởi những lời nói hay suy nghĩ của người khác',
  'Tôi thích chăm sóc sức khỏe cho người khác',
  'Tôi dễ cảm thụ văn học hay học một ngôn ngữ mới',
  'Tôi thích chia sẻ cho mọi người về những kiến thức mới học được',
  'Tôi thích chơi với trẻ em',
  'Tôi thường quan tâm đến cảm xúc của người khác trong giao tiếp',
  'Tôi thích tổ chức các hoạt động tập thể',
  'Tôi thích có nhiều mối quan hệ bạn bè',
  'Tôi thường nói chuyện trước đám đông',
  'Tôi thích giúp đỡ bạn bè khi gặp khó khăn',
  'Tôi thích các trò chơi hoặc các môn thể thao mang tính đồng đội cao',
  'Tôi thích tham dự các buổi hội họp'
]

export const quanLy = [
  'Tôi thích những hoạt động có tính mạo hiểm',
  'Tôi có khả năng đưa ra quyết định để giải quyết vấn đề',
  'Tôi là người năng động trong công việc',
  'Tôi thích cảm giác được nhiều người kính trọng, nể phục',
  'Tôi thấy mình có khả năng thuyết phục người khác',
  'Tôi thích làm các công việc quản lý và đánh giá',
  'Tôi thường đặt ra các mục tiêu, kế hoạch trong cuộc sống',
  'Tôi thường chiếm ưu thế khi tranh luận với người khác',
  'Tôi là người thích cạnh tranh và muốn mình giỏi hơn người khác',
  'Tôi thích được trở thành người lãnh đạo trong nhóm hoặc trong lớp',
  'Tôi có tính hiếu thắng',
  'Tôi thích tham gia vào các cuộc tranh luận về nhiều đề tài',
  'Tôi biết rõ điều mình muốn làm',
  'Tôi thích tham gia các cuộc thi để thể hiện bản thân',
  'Tôi không thích bỏ dở công việc giữa chừng',
  'Tôi cảm thấy hào hứng khi được tham gia các cuộc phiêu lưu',
  'Tôi là người cầu toàn, muốn mọi thứ phải đạt tiêu chuẩn',
  'Tôi thích tiết kiệm và quản lý tốt tiền bạc của mình',
  'Tôi thích việc lên kế hoạch, tổ chức, quản lý hay tổng hợp công việc của những thành viên khác trong nhóm',
  'Tôi thường xung phong vào ban đại diện học sinh ở trường',
  'Tôi thường được chỉ định làm lớp trưởng/lớp phó',
  'Tôi thích trải nghiệm các công việc kinh doanh như tự mình bán hàng trực tuyến',
  'Tôi muốn tự quản lý một cửa hàng của riêng mình',
  'Tôi thích tìm hiểu về thị trường chứng khoán',
  'Tôi thích tham gia các khóa học về quản trị kinh doanh',
  'Tôi thích các công việc đòi hỏi kỹ năng lãnh đạo',
  'Tôi thường là người lập kế hoạch khi làm việc nhóm',
  'Tôi thích đọc sách và tìm hiểu về những người thành công trong kinh doanh',
  'Tôi không cảm thấy ngại khi nói trước đám đông',
  'Tôi từng được thầy cô giao các công việc quản lý bạn học như sao đỏ, tổ trưởng',
  'Tôi biết cách thuyết phục bố mẹ/anh chị để đạt điều mình muốn',
  'Tôi có thể lên kế hoạch để tổ chức một buổi đi chơi cho cả gia đình',
  'Tôi muốn được đi làm thêm để tự kiếm tiền',
  'Tôi thường xung phong phát biểu trước lớp',
  'Tôi là người lập kế hoạch và phân công nhiệm vụ cho các thành viên nhóm',
  'Tôi rất hứng thú với việc khởi nghiệp',
  'Tôi thường được bạn bè bầu làm nhóm trưởng',
  'Tôi có khả năng dẫn dắt đội nhóm đạt mục tiêu đề ra',
  'Tôi có khả năng thuyết phục người khác nghe theo mình',
  'Tôi từng thử kinh doanh nhỏ với bạn bè',
  'Tôi rất tự tin với những quyết định của mình',
  'Tôi không gặp khó khăn khi giao tiếp với người lạ',
  'Tôi được nhiều thầy cô và bạn bè biết đến',
  'Tôi thường suy nghĩ về các ý tưởng kinh doanh trong tương lai',
  'Tôi có nhiều bạn bè quen biết và rất dễ làm quen bạn mới'
]

export const nghiepVu = [
  'Tôi là người có đầu óc sắp xếp, tổ chức',
  'Tôi có tính cẩn thận',
  'Tôi là người chu đáo, chính xác và đáng tin cậy',
  'Tôi thích công việc tính toán sổ sách, ghi chép số liệu',
  'Tôi thích các công việc lưu trữ, phân loại, cập nhật thông tin',
  'Tôi thường đặt ra những mục tiêu, kế hoạch trong cuộc sống',
  'Tôi thích làm việc với các con số, làm việc theo hướng dẫn, quy trình',
  'Tôi thích dự kiến các khoản thu chi',
  'Tôi thích lập thời khóa biểu, sắp xếp lịch làm việc',
  'Tôi thích mọi thứ được sắp xếp gọn gàng và ngăn nắp.',
  'Tôi thường xuyên lập danh sách chi tiết các công việc cần làm trong ngày hoặc trong một thời gian ngắn.',
  'Tôi thích đánh máy các tài liệu hơn là viết tay.',
  'Tôi rất thực tế, luôn cân nhắc kỹ về chi phí trước khi mua một thứ gì đó.',
  'Tôi thích đảm nhiệm vị trí thư ký trong các buổi họp hay họp nhóm.',
  'Tôi yêu thích việc sắp xếp, tổ chức công việc cho bản thân hoặc nhóm.',
  'Tôi tự thấy mình là người tỉ mỉ, chu đáo và cẩn thận.',
  'Tôi thích công việc tính toán sổ sách, ghi chép số liệu.',
  'Tôi thực sự bị cuốn hút bởi các hàm tính toán trong excel.',
  'Mở tài khoản tiết kiệm',
  'Lập kế hoạch chi tiêu hàng tháng',
  'Chuẩn bị ngân sách cho chuyến đi chơi tập thể lớp',
  'Chuẩn bị cho buổi trình bày trước lớp',
  'Lập kế hoạch cho kỳ nghỉ hè/Tết',
  'Đếm và sắp xếp tiền',
  'Sắp xếp lại bàn học',
  'Viết kế hoạch học tập cho học kỳ mới',
  'Hoàn tất bài tập theo đúng hạn được giao',
  'Dò lỗi chính tả cho phụ đề của một phim ưa thích',
  'Học một khóa vi tính văn phòng và biết cách sắp xếp văn bản, thư mục sao cho chỉn chu',
  'Làm thủ quỹ cho lớp',
  'Sắp xếp lại tủ quần áo cá nhân',
  'Giúp ba/mẹ quản lý tiền chợ của gia đình (mua gì, mua khi nào, mua bao nhiêu)',
  'Sắp xếp và ghi chú bài học theo quy tắc',
  'Tuân thủ luật lệ, quy tắc của trường lớp',
  'Dọn dẹp và sắp xếp bàn học định kỳ',
  'Thực hiện các việc cá nhân theo lịch cố định',
  'Làm việc theo sát quy trình, kế hoạch',
  'Tính lãi cho khoản vay ngân hàng',
  'Tính toán ngân sách thu chi cho một tổ chức',
  'Giữ và sắp xếp hồ sơ',
  'Tính toán lương và thuế cho người lao động',
  'Sắp xếp, đếm và lưu trữ vật tư của một công ty',
  'Tính toán hàng tồn kho trong một cửa hàng',
  'Cài đặt phần mềm đồng bộ trên các máy tính của một công ty',
  'Tạo bảng báo cáo chi tiết gồm cả biểu đồ, đồ thị, v.v.',
  'Tổ chức một sự kiện (tiệc, đám cưới, chương trình giải trí)',
  'Đặt mua văn phòng phẩm cho tất cả bộ phận của một công ty lớn',
  'Tìm lỗi trong tài khoản tài chính',
  'Mua sắm theo đơn đặt hàng của khách hàng trực tuyến',
  'Giữ hồ sơ chuyển và nhận hàng hoá',
  'Tạo một quy trình vận hành mới cho một tổ chức',
  'Thường sắp xếp vật dụng cá nhân theo trật tự và cách thức mà các con mong muốn',
  'Có thói quen hình dung và chuẩn bị các bước sẽ xảy ra trước khi tham gia một hoạt động',
  'Thường khó chịu khi có chuyện bất ngờ xảy ra',
  'Thường khó chịu khi một kế hoạch đã biết trước bị thay đổi vào phút chót',
  'Thoải mái khi làm việc theo nguyên tắc, trình tự, và kế hoạch cụ thể',
  'Thường sắp xếp thời khóa biểu bản thân và nghiêm túc tuân theo thời khoá biểu ấy',
  'Thường chủ động sắp xếp việc học chứ không cần đợi người lớn nhắc hay giúp',
  'Có khả năng phân loại và dọn dẹp phòng riêng, đồ vật riêng rất gọn gàng và ngăn nắp',
  'Thường chi tiêu hợp lý',
  'Thường hoàn thành hết trách nhiệm đã nhận trước khi giải trí hay nghỉ ngơi',
  'Có khi bị hiểu lầm bởi người khác là người cứng ngắc và quá nguyên tắc',
  'Thường tôn trọng cấp bậc và luật lệ trong sinh hoạt ở trường hay ở nhà',
  'Thường được thầy cô và bạn bè tin tưởng và giao các công việc liên quan đến chi tiêu hay thư ký',
  'Thường làm việc quá mức (ít ngủ, bỏ ăn, làm liên tục) khi gần tới hạn chót của một công việc nào đó'
]
